---
- hosts: '{{ target }}'
  strategy: free
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
     - raw: sudo apt-get update && sudo apt-get -y install python3-pip jq zstd git 
     - name: Include vars
       include_vars: 'stage_vars/{{ name }}/{{ stage }}/vars.yml'
     - name: Include vault
       include_vars: 'stage_vars/{{ name }}/{{ stage }}/vault.yml'
  roles:
    - { role: initialize_system }

- hosts: '{{ target }}'
  strategy: free
  become: yes
  become_user: '{{ deploy_user }}'
  pre_tasks:
     - name: Include vars
       include_vars: 'stage_vars/{{ name }}/{{ stage }}/vars.yml'
     - name: Include vault
       include_vars: 'stage_vars/{{ name }}/{{ stage }}/vault.yml'
  roles:
    - { role: build_source }
    - { role: deploy_node }